export type { WorktreeStatus, WorktreeMeta } from "./meta.js";
export { metaDirForRun, readMeta, writeMeta, updateStatus, isOrphanWorktree } from "./meta.js";
export type { CreateWorktreeOpts, CreateWorktreeResult } from "./create.js";
export { createWorktree } from "./create.js";
export type { MergeOpts, MergeResult } from "./merge.js";
export { mergeWorktree } from "./merge.js";
export type { CleanOpts, CleanResult } from "./clean.js";
export { cleanWorktrees } from "./clean.js";
export type { WorktreeListEntry } from "./list.js";
export { listWorktreeMetas } from "./list.js";
